"""empty message

Revision ID: b6dbccd73bba
Revises: e2c86ad35888
Create Date: 2021-06-02 00:28:57.750403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6dbccd73bba'
down_revision = 'e2c86ad35888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('ingredients', sa.String(length=800), nullable=False),
    sa.Column('instructions', sa.String(length=800), nullable=False),
    sa.Column('descriptions', sa.String(length=800), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_recipe')
    # ### end Alembic commands ###
